class Fields:
    FORM_NAME = "name"
    FORM_SURNAME = "surname"
    FORM_FULL_NAME = "full_name"
    FORM_NIF = "nif"
    FORM_GENDER = "gender"
    FORM_BIRTH = "birth"
    FORM_CATEGORY = "category"
    FORM_NATIONALITY = "nationality"

    FORM_ADDRESS = "address"
    FORM_ADDRESS_NUMBER = "address_number"
    FORM_POSTAL_CODE = "postal_code"
    FORM_TOWN = "town"
    FORM_STATE = "state"
    FORM_COUNTRY = "country"
    FORM_PHONE = "phone"
    FORM_EMAIL = "email"

    FORM_ENTITY = "entity"
    FORM_ENTITY_ADDRESS = "entity_address"
    FORM_ENTITY_STATE = "entity_state"

    FORM_SIGN_IN = "sign_in"
    FORM_SIGN_ON_DAY = "sign_on_day"
    FORM_SIGN_ON_MONTH = "sign_on_month"
    FORM_SIGN_ON_YEAR = "sign_on_year"

    FORM_ROWER = "checkbox_rower"
    FORM_COACH = "checkbox_coach"
    FORM_DIRECTIVE = "checkbox_directive"
