################
#   RACE TYPE  #
################
RACE_CONVENTIONAL = 'CONVENTIONAL'
RACE_TIME_TRIAL = 'TIME_TRIAL'

################
#  MODALITIES  #
################
RACE_TRAINERA = 'TRAINERA'
RACE_TRAINERILLA = 'TRAINERILLA'
RACE_BATEL = 'BATEL'

################
#  CATEGORIES  #
################
PARTICIPANT_CATEGORY_ABSOLUT = 'ABSOLUT'
PARTICIPANT_CATEGORY_VETERAN = 'VETERAN'
PARTICIPANT_CATEGORY_SCHOOL = 'SCHOOL'

################
#   ENTITIES   #
################
ENTITY_CLUB = 'CLUB'
ENTITY_LEAGUE = 'LEAGUE'
ENTITY_FEDERATION = 'FEDERATION'
ENTITY_PRIVATE = 'PRIVATE'

################
#   GENDERS    #
################
GENDER_MALE = 'MALE'
GENDER_FEMALE = 'FEMALE'
GENDER_MIX = 'MIX'

################
#  PENALTIES   #
################
NO_LINE_START = 'NO_LINE_START'
NULL_START = 'NULL_START'
BLADE_TOUCH = 'BLADE_TOUCH'
